mkdocs:
  stage: build
  image: python:3.9
  artifacts:
    paths:
      - site
  before_script:
    - pip install pipenv
    - pipenv install
  script:
    - pipenv run mkdocs build


salt:
  stage: deploy
  image: registry.gitlab.com/spirostack/spiro-deploy:master
  only:
    - master
  environment:
    name: Live
    url: https://lumami.biz/
  dependencies:
    - mkdocs
  script:
    spiro-deploy lumami.biz prod --highstate --artifact=site
